feat: allow configuring delay for validation
natemcmaster/LettuceEncrypt pull request #259
Opened 2022-06-15 11:37 UTC by h3rmanj

Fixes #254 

This PR adds an optional `ChallengeValidationDelayMs` to the configuration, allowing consumers to specify a delay before the challenge is ready for validation.

The delay happens in the `AcmeClient.ValidateChallengeAsync`, which is only used by the HTTP01 and TLSAlpn01 validators, as far as I can see. I don't know if it should rather be in the `Http01DomainValidator.PrepareHttpChallengeAsync` / `TlsAlpn01DomainValidator.PrepareTlsAlpnChallengeResponseAsync`, but there I don't have access to the configuration without changing the `AcmeCertificateFactory`.

2022-06-19 18:57 UTC, natemcmaster requested changes
Thanks for making a pull request! Can you check the build failures on the CI workflow?

2022-06-19 19:18 UTC, h3rmanj commented
Apparently had some extra whitespace. Ran the build script locally which automatically fixed it for me and passed locally 🙂

2022-06-21 08:10 UTC, h3rmanj commented
I've looked at the failing build for macos, but I can't find it's related to anything i made.

While delaying x amount could work in my scenario, it is a workaround and probably not an optimal solution to add to the library. I think a better solution would be to have a shared validation challenge store, which instances of my application could read and write to, no matter which one requested the domain validation.

After looking through the internals of this library, I think `IHttpChallengeResponseStore` might be a good place to hook into. It's internal right now, but making it public (and async) would allow consumers to implement their custom store, and also let it be implemented in the Azure integration.

I'll copy this text in the original issue where we can continue the discussion if you have feedback, and I'll try to make another PR. Sorry for taking your time with this PR.

2022-06-21 08:10 UTC, closed without merging

2022-06-23 02:18 UTC, natemcmaster commented
Thanks for taking a look at the issue!